[package]
name = "hello"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dotenv = "0.15.0"
salvo = { version = '*', features = ["cors"]}
serde = "1.0.197"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
